### ISSUE TITLE
Depends on broken package sdl1

### ISSUE THREAD

**Issue by wizzardx** [Vladar4/libtcod_nim#6]
This command:

```
./build_samples
```
results in this error:

```
/home/david/.nimble/pkgs/sdl1-1.0.0/sdl.nim(1064, 27) Error: undeclared identifier: 'expr'

```

**Comment by Vladar4** [comment]
sdl1fixed it in https://github.com/nim-lang/sdl1/commit/7fd5f49502ccce2f7fe2762a48d207a9675007f3

**Comment by Skaruts** [comment]
@Vladar4 Since you're mentioning `sdl` in this older issue, I'm a bit confused. As of now, does this package depend on the official `sdl` package, or your `sdl_nim` package? 

Some things seem to work with both, but the samples112 seem to only work with `sdl_nim`. The nimble file contains no dependencies related to SDL, and the readme also doesn't say which one should be installed...

**Comment by Vladar4** [comment]
Ah yes, the 1.5 branch uses SDL1, newer ones use SDL2 (sdl2_nim).

It could be rewritten by embedding `ptrMath` template from sdl2_nim into the samples.nim code. Should be fine now, just uncomment the appropriate imports: dfc12aedbc9bbc09d22147d60f41e15471aedb09

**Comment by Skaruts** [comment]
Oh, actually I was forgetting there's two SDLs... I meant [`sdl2`](https://github.com/nim-lang/sdl2) and `sdl2_nim`. But you answered the question, anyway. :)

Alright then. I think I have everything as it should be. Thanks.
